// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';
import {window} from '../models';

export function AdjustWindowfromLeftBottom(arg1:number,arg2:number):Promise<void>;

export function SetContext(arg1:context.Context):Promise<void>;

export function UpdatePetHitbox(arg1:window.PetHitbox):Promise<void>;
