// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AdjustWindowfromLeftBottom(arg1, arg2) {
  return window['go']['window']['WindowService']['AdjustWindowfromLeftBottom'](arg1, arg2);
}

export function SetContext(arg1) {
  return window['go']['window']['WindowService']['SetContext'](arg1);
}

export function UpdatePetHitbox(arg1) {
  return window['go']['window']['WindowService']['UpdatePetHitbox'](arg1);
}
