// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {items} from '../models';

export function LoadAllItems():Promise<Array<items.Item>>;

export function LoadItemByID(arg1:number):Promise<items.Item>;

export function LoadItemFrameByID(arg1:number):Promise<string>;

export function Shutdown():Promise<void>;
