// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function LoadAllItems() {
  return window['go']['items']['ItemsMeta']['LoadAllItems']();
}

export function LoadItemByID(arg1) {
  return window['go']['items']['ItemsMeta']['LoadItemByID'](arg1);
}

export function LoadItemFrameByID(arg1) {
  return window['go']['items']['ItemsMeta']['LoadItemFrameByID'](arg1);
}

export function Shutdown() {
  return window['go']['items']['ItemsMeta']['Shutdown']();
}
