// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';

export function Greet(arg1:string):Promise<string>;

export function PetSprite():Promise<string>;

export function PetSpriteBy(arg1:string):Promise<string>;

export function Quit():Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;
