// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {activities} from '../models';
import {items} from '../models';

export function LoadAllActivities():Promise<Array<activities.ActivityWithFrames>>;

export function LoadAllItems():Promise<Array<items.ItemWithFrame>>;

export function PerformActivity(arg1:activities.Activity):Promise<void>;

export function PetFrames():Promise<Array<string>>;

export function PetFramesBy(arg1:string):Promise<Array<string>>;

export function Quit():Promise<void>;

export function UseItem(arg1:items.Item):Promise<void>;
