// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function PetFrames():Promise<Array<string>>;

export function PetFramesBy(arg1:string):Promise<Array<string>>;
