// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function LoadAllActivities() {
  return window['go']['app']['App']['LoadAllActivities']();
}

export function LoadAllItems() {
  return window['go']['app']['App']['LoadAllItems']();
}

export function PerformActivity(arg1) {
  return window['go']['app']['App']['PerformActivity'](arg1);
}

export function PetFrames() {
  return window['go']['app']['App']['PetFrames']();
}

export function PetFramesBy(arg1) {
  return window['go']['app']['App']['PetFramesBy'](arg1);
}

export function Quit() {
  return window['go']['app']['App']['Quit']();
}

export function UseItem(arg1) {
  return window['go']['app']['App']['UseItem'](arg1);
}
