// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function PetFrames() {
  return window['go']['app']['App']['PetFrames']();
}

export function PetFramesBy(arg1) {
  return window['go']['app']['App']['PetFramesBy'](arg1);
}
