// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChatWithPet(arg1) {
  return window['go']['chat']['ChatMeta']['ChatWithPet'](arg1);
}

export function Shutdown() {
  return window['go']['chat']['ChatMeta']['Shutdown']();
}
