// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChatWithPet(arg1:string):Promise<string>;

export function Shutdown():Promise<void>;
