// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetPetStatus() {
  return window['go']['pet']['PetMeta']['GetPetStatus']();
}

export function PerformActivity(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9) {
  return window['go']['pet']['PetMeta']['PerformActivity'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);
}

export function PetFrames() {
  return window['go']['pet']['PetMeta']['PetFrames']();
}

export function PetFramesBy(arg1) {
  return window['go']['pet']['PetMeta']['PetFramesBy'](arg1);
}

export function PetFramesDrag() {
  return window['go']['pet']['PetMeta']['PetFramesDrag']();
}

export function PetFramesDrop() {
  return window['go']['pet']['PetMeta']['PetFramesDrop']();
}

export function PetFramesMoveFar() {
  return window['go']['pet']['PetMeta']['PetFramesMoveFar']();
}

export function PetFramesMoveLeft() {
  return window['go']['pet']['PetMeta']['PetFramesMoveLeft']();
}

export function PetFramesMoveRight() {
  return window['go']['pet']['PetMeta']['PetFramesMoveRight']();
}

export function PetFramesStand() {
  return window['go']['pet']['PetMeta']['PetFramesStand']();
}

export function Service(arg1) {
  return window['go']['pet']['PetMeta']['Service'](arg1);
}

export function Shutdown() {
  return window['go']['pet']['PetMeta']['Shutdown']();
}

export function StopActivity() {
  return window['go']['pet']['PetMeta']['StopActivity']();
}

export function UpdateStatus(arg1) {
  return window['go']['pet']['PetMeta']['UpdateStatus'](arg1);
}

export function UseItemByID(arg1) {
  return window['go']['pet']['PetMeta']['UseItemByID'](arg1);
}
