// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {pet} from '../models';
import {context} from '../models';
import {attributes} from '../models';

export function GetPetStatus():Promise<pet.Pet>;

export function PerformActivity(arg1:string,arg2:number,arg3:number,arg4:number,arg5:number,arg6:number,arg7:number,arg8:number,arg9:number):Promise<void>;

export function PetFrames():Promise<Array<string>>;

export function PetFramesBy(arg1:string):Promise<Array<string>>;

export function PetFramesDrag():Promise<Array<string>>;

export function PetFramesDrop():Promise<Array<string>>;

export function PetFramesMoveFar():Promise<Array<string>>;

export function PetFramesMoveLeft():Promise<Array<string>>;

export function PetFramesMoveRight():Promise<Array<string>>;

export function PetFramesStand():Promise<Array<string>>;

export function Service(arg1:context.Context):Promise<void>;

export function Shutdown():Promise<void>;

export function StopActivity():Promise<void>;

export function UpdateStatus(arg1:attributes.Attributes):Promise<void>;

export function UseItemByID(arg1:number):Promise<void>;
