// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {activities} from '../models';

export function LoadActivityFramesByID(arg1:number):Promise<Array<string>>;

export function LoadAll():Promise<Array<activities.Activity>>;

export function LoadAllActivities():Promise<Array<activities.Activity>>;

export function LoadFramesByID(arg1:number):Promise<Array<string>>;

export function Shutdown():Promise<void>;
