// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function LoadActivityFramesByID(arg1) {
  return window['go']['activities']['ActivityMeta']['LoadActivityFramesByID'](arg1);
}

export function LoadAll() {
  return window['go']['activities']['ActivityMeta']['LoadAll']();
}

export function LoadAllActivities() {
  return window['go']['activities']['ActivityMeta']['LoadAllActivities']();
}

export function LoadFramesByID(arg1) {
  return window['go']['activities']['ActivityMeta']['LoadFramesByID'](arg1);
}

export function Shutdown() {
  return window['go']['activities']['ActivityMeta']['Shutdown']();
}
